services:
  postgres:
    image: postgres:18
    container_name: repoTracker-postgres

    environment:
      POSTGRES_USER: repoTrackerUser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: repoTracker

    ports:
      - "5432:5432"

    volumes:
      - repoTracker-postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repoTrackerUser -d repoTracker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  repoTracker-postgres-data: